import "@testing-library/jest-dom/vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach } from "vitest";

import { TaskBoard } from "../TaskBoard";
import { MemoryBackend } from "../../backend/memory-backend";
import { isGeneratedByUs } from "../../domain/devlog-render";

let backend: MemoryBackend;

beforeEach(async () => {
  backend = new MemoryBackend();
  const task = await backend.createTask("offline sdk with mock storage", { status: "in_progress" });
  await backend.setTaskLabels(task.id, ["OfflineSDK"]);
  await backend.addTaskEvent(task.id, "note", "picked this back up");
});

function renderBoard(over: Record<string, unknown> = {}) {
  return render(
    <TaskBoard
      backend={backend}
      workstreams={[]}
      projects={[]}
      onClose={vi.fn()}
      devlogDirectory="/wiki/devlog/fy2027"
      {...over}
    />,
  );
}

describe("devlog export", () => {
  it("previews the page without writing anything", async () => {
    renderBoard();
    await screen.findByText("offline sdk with mock storage");

    fireEvent.click(screen.getByTestId("devlog-preview"));

    const preview = await screen.findByTestId("devlog-preview-content");
    expect(preview.textContent).toContain("offline sdk with mock storage");
    expect(preview.textContent).toContain("picked this back up");
    // The whole point of a preview is that nothing reaches the wiki.
    expect(backend._devlogFiles.size).toBe(0);
  });

  it("writes a valid generated page on export", async () => {
    renderBoard();
    await screen.findByText("offline sdk with mock storage");

    fireEvent.click(screen.getByTestId("devlog-export"));

    await waitFor(() => expect(backend._devlogFiles.size).toBe(1));
    const [content] = [...backend._devlogFiles.values()];
    expect(isGeneratedByUs(content)).toBe(true);
    expect(content).toContain("offline sdk with mock storage");
  });

  it("reports where it wrote and whether it committed", async () => {
    renderBoard();
    await screen.findByText("offline sdk with mock storage");
    fireEvent.click(screen.getByTestId("devlog-export"));

    const status = await screen.findByTestId("devlog-status");
    expect(status.textContent).toMatch(/wiki\/devlog\/fy2027/);
  });

  it("surfaces the warning when it had to write alongside a hand-written page", async () => {
    // Reproduces the real hazard: a year of hand-written days share the folder.
    backend._devlogFiles.set(
      `/wiki/devlog/fy2027/${new Date().toISOString().slice(0, 10)}.md`,
      "## AudioTranscoding\n- 👁️Waiting on Marcus\n",
    );
    renderBoard();
    await screen.findByText("offline sdk with mock storage");
    fireEvent.click(screen.getByTestId("devlog-export"));

    const status = await screen.findByTestId("devlog-status");
    await waitFor(() => expect(status.textContent).toMatch(/not generated by Workstreams/));
  });

  it("refuses to export when no devlog folder is configured", async () => {
    renderBoard({ devlogDirectory: "" });
    await screen.findByText("offline sdk with mock storage");
    fireEvent.click(screen.getByTestId("devlog-export"));

    const status = await screen.findByTestId("devlog-status");
    expect(status.textContent).toMatch(/not configured/i);
    expect(backend._devlogFiles.size).toBe(0);
  });

  it("still previews with no folder configured, since preview writes nothing", async () => {
    renderBoard({ devlogDirectory: "" });
    await screen.findByText("offline sdk with mock storage");
    fireEvent.click(screen.getByTestId("devlog-preview"));
    expect(await screen.findByTestId("devlog-preview-content")).toBeInTheDocument();
  });
});
