export type DangerCategory = "git" | "node_modules" | "build_artifact" | "lockfile";

export interface DangerHit {
  category: DangerCategory;
  /** The subtree root (path up to and including the matched dir) for which a
   *  warning should be remembered per-session, OR the full path for lockfiles. */
  warningKey: string;
  /** Human-readable reason for the warning dialog. */
  reason: string;
}

const LOCKFILE_NAMES = new Set([
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "Cargo.lock",
  "poetry.lock",
]);

const LOCKFILE_REASON =
  "Lockfiles are managed by your package manager and editing them by hand may cause inconsistent installs.";

const SUBTREE_REASONS = new Map<string, Omit<DangerHit, "warningKey">>([
  [
    ".git",
    {
      category: "git",
      reason: "Editing files inside the .git directory can corrupt your repo state.",
    },
  ],
  [
    "node_modules",
    {
      category: "node_modules",
      reason:
        "Files under node_modules are managed by your package manager and will be overwritten by `npm install`.",
    },
  ],
  [
    "target",
    {
      category: "build_artifact",
      reason: "Files under target/ are generated by Cargo and will be overwritten on next build.",
    },
  ],
  [
    "dist",
    {
      category: "build_artifact",
      reason: "Files under dist/ are generated build artifacts and will be overwritten on next build.",
    },
  ],
  [
    "build",
    {
      category: "build_artifact",
      reason: "Files under build/ are generated build artifacts and will be overwritten on next build.",
    },
  ],
  [
    ".next",
    {
      category: "build_artifact",
      reason: "Files under .next/ are generated by Next.js and will be overwritten on next build.",
    },
  ],
]);

const normalizePath = (absolutePath: string) => absolutePath.replace(/\\/g, "/");

const splitPath = (path: string) => path.split("/").filter((segment) => segment.length > 0);

const subtreeWarningKey = (normalizedPath: string, segmentIndex: number, segment: string) => {
  const prefix = normalizedPath.startsWith("/") ? "/" : "";
  return `${prefix}${splitPath(normalizedPath).slice(0, segmentIndex + 1).join("/")}` || segment;
};

/**
 * Check whether saving to `absolutePath` should trigger a dangerous-path warning.
 * Paths must be absolute and normalized by the caller; both slash styles are accepted.
 */
export function classifyDangerousPath(absolutePath: string): DangerHit | null {
  const normalizedPath = normalizePath(absolutePath);
  const segments = splitPath(normalizedPath);
  const basename = segments[segments.length - 1];

  if (basename !== undefined && LOCKFILE_NAMES.has(basename)) {
    return {
      category: "lockfile",
      warningKey: normalizedPath,
      reason: LOCKFILE_REASON,
    };
  }

  for (const [index, segment] of segments.entries()) {
    const subtreeHit = SUBTREE_REASONS.get(segment);

    if (subtreeHit !== undefined) {
      return {
        ...subtreeHit,
        warningKey: subtreeWarningKey(normalizedPath, index, segment),
      };
    }
  }

  return null;
}
