//! Devlog export.
//!
//! Writes a generated day page into the user's wiki and, optionally, commits
//! and pushes it. This is the highest blast-radius code in the application:
//! the target folder holds a year of hand-written work log that exists in no
//! other form, and a bad overwrite would be unrecoverable.
//!
//! The guard is therefore conservative in one specific direction. A file is
//! only ever replaced if it *proves* it came from us, by carrying our
//! `generated_by` key inside leading YAML front matter. Anything else -- a
//! hand-written page, a page with somebody else's front matter, an empty file,
//! an unreadable file -- causes the export to write alongside under a
//! `.workstreams.md` suffix and report a warning, rather than to guess.
//!
//! Export is one-way by design. Nothing here ever reads a page back into the
//! database, so the wiki stays a searchable archive rather than a second
//! source of truth that would need conflict resolution.

use serde::Serialize;
use std::path::{Path, PathBuf};

/// Front-matter key proving a page came from this app. Must stay identical to
/// `GENERATED_BY_MARKER` in `src/domain/devlog-render.ts`.
const GENERATED_BY_MARKER: &str = "generated_by: workstreams";

#[derive(Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DevlogExportResult {
    /// Absolute path actually written.
    pub path: String,
    /// True when the intended path was occupied by a file we did not generate.
    pub wrote_alongside: bool,
    /// Non-fatal explanation shown to the user; empty when all went well.
    pub warning: String,
    /// Commit SHA, or empty when committing was skipped or failed.
    pub commit: String,
    /// True when the commit was pushed to the remote.
    pub pushed: bool,
}

/// Whether a page was produced by our renderer.
///
/// Strict on purpose: only leading front matter containing our exact marker
/// counts. See the module docs for why the failure mode has to be "refuse",
/// not "assume".
pub fn is_generated_by_us(content: &str) -> bool {
    let Some(rest) = content.strip_prefix("---\n") else {
        return false;
    };
    match rest.find("\n---") {
        Some(end) => rest[..end].contains(GENERATED_BY_MARKER),
        None => false,
    }
}

/// Decide where a day's page may safely be written.
///
/// Returns the target path and, when the intended file is not ours, a warning
/// explaining why we stepped aside.
pub fn resolve_target(dir: &Path, date: &str) -> (PathBuf, Option<String>) {
    let intended = dir.join(format!("{date}.md"));
    if !intended.exists() {
        return (intended, None);
    }

    match std::fs::read_to_string(&intended) {
        Ok(existing) if is_generated_by_us(&existing) => (intended, None),
        Ok(_) => (
            dir.join(format!("{date}.workstreams.md")),
            Some(format!(
                "{}.md was not generated by Workstreams, so it was left untouched \
                 and the export was written alongside it.",
                date
            )),
        ),
        // An unreadable file is not a licence to replace it.
        Err(e) => (
            dir.join(format!("{date}.workstreams.md")),
            Some(format!(
                "{}.md could not be read ({e}), so it was left untouched and the \
                 export was written alongside it.",
                date
            )),
        ),
    }
}

fn git(dir: &Path, args: &[&str]) -> Result<String, String> {
    let out = crate::git_command()
        .current_dir(dir)
        .args(args)
        .output()
        .map_err(|e| format!("git {}: {e}", args.join(" ")))?;
    if !out.status.success() {
        return Err(String::from_utf8_lossy(&out.stderr).trim().to_string());
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

/// Write the page, then optionally commit and push it.
///
/// Commit and push failures are reported but never discard the written file:
/// losing the day's export because a remote was unreachable would be a worse
/// outcome than an uncommitted file the user can commit later.
pub fn write_and_commit(
    dir: &Path,
    date: &str,
    content: &str,
    commit: bool,
    push: bool,
) -> Result<DevlogExportResult, String> {
    if !dir.is_dir() {
        return Err(format!(
            "devlog directory does not exist: {}",
            dir.display()
        ));
    }

    let (path, warning) = resolve_target(dir, date);
    let wrote_alongside = warning.is_some();

    std::fs::write(&path, content).map_err(|e| format!("write {}: {e}", path.display()))?;

    let mut result = DevlogExportResult {
        path: path.display().to_string(),
        wrote_alongside,
        warning: warning.unwrap_or_default(),
        commit: String::new(),
        pushed: false,
    };

    if !commit {
        return Ok(result);
    }

    let file_name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    if let Err(e) = git(dir, &["add", &file_name]) {
        result.warning = join_warning(&result.warning, &format!("git add failed: {e}"));
        return Ok(result);
    }

    // Nothing staged means the page is unchanged since the last export, which
    // is a perfectly normal no-op rather than an error.
    if git(dir, &["diff", "--cached", "--quiet"]).is_ok() {
        result.warning = join_warning(&result.warning, "no changes to commit");
        return Ok(result);
    }

    let message = format!("devlog: {date}");
    if let Err(e) = git(dir, &["commit", "-m", &message]) {
        result.warning = join_warning(&result.warning, &format!("git commit failed: {e}"));
        return Ok(result);
    }

    result.commit = git(dir, &["rev-parse", "HEAD"]).unwrap_or_default();

    if push {
        match git(dir, &["push"]) {
            Ok(_) => result.pushed = true,
            Err(e) => {
                result.warning = join_warning(&result.warning, &format!("git push failed: {e}"));
            }
        }
    }

    Ok(result)
}

fn join_warning(existing: &str, extra: &str) -> String {
    if existing.is_empty() {
        extra.to_string()
    } else {
        format!("{existing} {extra}")
    }
}

/// Render is done in TypeScript; this command only persists the result.
#[tauri::command]
pub fn export_devlog_day(
    directory: String,
    date: String,
    content: String,
    commit: Option<bool>,
    push: Option<bool>,
) -> Result<DevlogExportResult, String> {
    write_and_commit(
        Path::new(&directory),
        &date,
        &content,
        commit.unwrap_or(true),
        push.unwrap_or(false),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "ws_devlog_{}_{}_{}",
            tag,
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    const GENERATED: &str =
        "---\ndate: 2026-08-19\ngenerated_by: workstreams\n---\n\n# 2026-08-19\n";

    /// A real hand-written page, copied in shape from the user's archive.
    const HAND_WRITTEN: &str = "## AudioTranscoding\n\
        - 👁️Waiting on Marcus for bug fix review\n\
        \t- ✅This one couldnt replicate, seems to be a no issue\n";

    #[test]
    fn recognises_its_own_output() {
        assert!(is_generated_by_us(GENERATED));
    }

    #[test]
    fn refuses_to_claim_a_hand_written_page() {
        assert!(!is_generated_by_us(HAND_WRITTEN));
    }

    #[test]
    fn refuses_front_matter_that_is_not_ours() {
        assert!(!is_generated_by_us(
            "---\ndate: 2026-08-19\ntags: [work]\n---\n# hi\n"
        ));
    }

    #[test]
    fn refuses_an_empty_or_truncated_file() {
        assert!(!is_generated_by_us(""));
        assert!(!is_generated_by_us(
            "---\ndate: 2026-08-19\ngenerated_by: workstreams\n"
        ));
    }

    #[test]
    fn writes_straight_to_the_day_file_when_nothing_is_there() {
        let dir = temp_dir("fresh");
        let result = write_and_commit(&dir, "2026-08-19", GENERATED, false, false).unwrap();
        assert!(result.path.ends_with("2026-08-19.md"));
        assert!(!result.wrote_alongside);
        assert!(result.warning.is_empty());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn replaces_a_page_it_generated_earlier() {
        let dir = temp_dir("regen");
        std::fs::write(dir.join("2026-08-19.md"), GENERATED).unwrap();
        let updated = format!("{GENERATED}\n## New section\n");
        let result = write_and_commit(&dir, "2026-08-19", &updated, false, false).unwrap();

        assert!(!result.wrote_alongside);
        let on_disk = std::fs::read_to_string(dir.join("2026-08-19.md")).unwrap();
        assert!(on_disk.contains("New section"));
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn never_overwrites_a_hand_written_day() {
        // The single most important test in this module: the user's archive is
        // a year of work that exists nowhere else.
        let dir = temp_dir("handwritten");
        let target = dir.join("2026-08-19.md");
        std::fs::write(&target, HAND_WRITTEN).unwrap();

        let result = write_and_commit(&dir, "2026-08-19", GENERATED, false, false).unwrap();

        assert!(result.wrote_alongside);
        assert!(result.path.ends_with("2026-08-19.workstreams.md"));
        assert!(!result.warning.is_empty());
        assert_eq!(
            std::fs::read_to_string(&target).unwrap(),
            HAND_WRITTEN,
            "the hand-written page was modified"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn errors_rather_than_creating_a_missing_devlog_directory() {
        // Silently creating the folder would hide a mistyped path and scatter
        // generated pages somewhere the user never looks.
        let dir = temp_dir("missing").join("nope");
        let err = write_and_commit(&dir, "2026-08-19", GENERATED, false, false).unwrap_err();
        assert!(err.contains("does not exist"));
    }

    #[test]
    fn commits_the_page_in_a_git_repo() {
        let dir = temp_dir("git");
        for args in [
            vec!["init", "-q"],
            vec!["config", "user.email", "test@example.com"],
            vec!["config", "user.name", "Test"],
        ] {
            git(&dir, &args).unwrap();
        }

        let result = write_and_commit(&dir, "2026-08-19", GENERATED, true, false).unwrap();
        assert!(!result.commit.is_empty(), "warning was: {}", result.warning);
        assert!(!result.pushed);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn reports_a_commit_failure_without_discarding_the_written_page() {
        // Not a git repo, so committing cannot work -- but the file the user
        // asked for must still be on disk.
        let dir = temp_dir("nogit");
        let result = write_and_commit(&dir, "2026-08-19", GENERATED, true, false).unwrap();

        assert!(result.commit.is_empty());
        assert!(!result.warning.is_empty());
        assert!(dir.join("2026-08-19.md").exists());
        std::fs::remove_dir_all(&dir).ok();
    }
}
