import { describe, expect, it } from "vitest";

import { classifyDangerousPath, type DangerCategory } from "../dangerousPaths";

const expectHit = (path: string, category: DangerCategory, warningKey: string, reason: string) => {
  expect(classifyDangerousPath(path)).toEqual({ category, warningKey, reason });
};

describe("classifyDangerousPath", () => {
  it("matches .git subtrees with a shared warning key", () => {
    const reason = "Editing files inside the .git directory can corrupt your repo state.";

    expectHit("/home/x/repo/.git/config", "git", "/home/x/repo/.git", reason);
    expectHit("/home/x/repo/.git/refs/heads/master", "git", "/home/x/repo/.git", reason);
  });

  it("handles mixed Windows separators", () => {
    expectHit(
      "C:\\repo\\.git\\config",
      "git",
      "C:/repo/.git",
      "Editing files inside the .git directory can corrupt your repo state.",
    );
  });

  it("matches node_modules subtrees", () => {
    expectHit(
      "/repo/node_modules/react/index.js",
      "node_modules",
      "/repo/node_modules",
      "Files under node_modules are managed by your package manager and will be overwritten by `npm install`.",
    );
  });

  it.each([
    ["target", "/repo/target/debug/app", "Files under target/ are generated by Cargo and will be overwritten on next build."],
    ["dist", "/repo/dist/assets/app.js", "Files under dist/ are generated build artifacts and will be overwritten on next build."],
    ["build", "/repo/build/output.js", "Files under build/ are generated build artifacts and will be overwritten on next build."],
    [".next", "/repo/.next/server/page.js", "Files under .next/ are generated by Next.js and will be overwritten on next build."],
  ])("matches %s build artifact subtrees", (_dirName, path, reason) => {
    const warningKey = path.split("/").slice(0, 3).join("/");

    expectHit(path, "build_artifact", warningKey, reason);
  });

  it("does not match dangerous directory names as substrings", () => {
    expect(classifyDangerousPath("/repo/mytarget/foo.txt")).toBeNull();
    expect(classifyDangerousPath("/repo/.git_backup/foo")).toBeNull();
    expect(classifyDangerousPath("/repo/node_modules_backup/react/index.js")).toBeNull();
  });

  it.each([
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "Cargo.lock",
    "poetry.lock",
  ])("matches %s by basename only", (basename) => {
    const path = `/any/parent/${basename}`;

    expectHit(
      path,
      "lockfile",
      path,
      "Lockfiles are managed by your package manager and editing them by hand may cause inconsistent installs.",
    );
  });

  it("prefers a lockfile match inside node_modules", () => {
    expectHit(
      "/repo/node_modules/pkg/package-lock.json",
      "lockfile",
      "/repo/node_modules/pkg/package-lock.json",
      "Lockfiles are managed by your package manager and editing them by hand may cause inconsistent installs.",
    );
  });

  it("returns null for non-dangerous paths", () => {
    expect(classifyDangerousPath("/repo/src/files/bufferState.ts")).toBeNull();
  });
});
